[INFO   ] Logger: Record log in /storage/emulated/0/AnonNet/SeginUp/.kivy/logs/kivy_22-04-13_0.txt
[WARNING] [Config      ] Upgrading configuration in progress.
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[ERROR  ] Error when copying logo directory
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py", line 343, in <module>
    shutil.copytree(join(kivy_data_dir, 'logo'), icon_dir)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/shutil.py", line 565, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/shutil.py", line 521, in _copytree
    raise Error(errors)
shutil.Error: [('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-128.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-128.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-512.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-512.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-16.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-16.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-32.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-32.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-48.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-48.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-64.ico', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-64.ico', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-24.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-24.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-256.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-256.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo/kivy-icon-64.png', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon/kivy-icon-64.png', '[Errno 1] Operation not permitted'), ('/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/data/logo', '/storage/emulated/0/AnonNet/SeginUp/.kivy/icon', '[Errno 1] Operation not permitted')]
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] KivyMD: 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.1 v1.r12p1-03dev0.0f7d1513832965c37da480ab8c6a8893'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T720'>
[INFO   ] GL: OpenGL parsed version: 3, 1
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/AnonNet/SeginUp/seginup.py", line 2, in <module>
[WARNING] stderr:     from kiby.lang import Builder
[WARNING] stderr: ModuleNotFoundError: No module named 'kiby'
