[INFO   ] Logger: Record log in /storage/emulated/0/AnonNet/SeginUp/.kivy/logs/kivy_22-04-13_4.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] KivyMD: 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.1 v1.r12p1-03dev0.0f7d1513832965c37da480ab8c6a8893'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T720'>
[INFO   ] GL: OpenGL parsed version: 3, 1
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 701, in _apply_rule
[WARNING] stderr:     setattr(widget_set, key, value)
[WARNING] stderr:   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
[WARNING] stderr:   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
[WARNING] stderr:   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
[WARNING] stderr:   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/label.py", line 354, in _trigger_texture_update
[WARNING] stderr:     self._create_label()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/label.py", line 347, in _create_label
[WARNING] stderr:     self._label = CoreMarkupLabel(**dkw)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/markup.py", line 94, in __init__
[WARNING] stderr:     super(MarkupLabel, self).__init__(*largs, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 288, in __init__
[WARNING] stderr:     self.resolve_font_name()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 356, in resolve_font_name
[WARNING] stderr:     raise IOError('Label: File %r not found' % fontname)
[WARNING] stderr: OSError: Label: File 'assets/nasa.ttf' not found
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/AnonNet/SeginUp/seginup.py", line 11, in <module>
[WARNING] stderr:     SeginUpApp().run()
[WARNING] stderr:   File "/storage/emulated/0/AnonNet/SeginUp/seginup.py", line 6, in __init__
[WARNING] stderr:     self.builder = Builder.load_file('style.kv')
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 306, in load_file
[WARNING] stderr:     return self.load_string(data, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 408, in load_string
[WARNING] stderr:     self._apply_rule(
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
[WARNING] stderr:     raise BuilderException(rule.ctx, rule.line,
[WARNING] stderr: kivy.lang.builder.BuilderException: Parser: File "/storage/emulated/0/AnonNet/SeginUp/style.kv", line 18:
[WARNING] stderr: ...
[WARNING] stderr:      16:            font_size: 80
[WARNING] stderr:      17:            bold: True
[WARNING] stderr: >>   18:            markup: True
[WARNING] stderr:      19:            halign: "center"
[WARNING] stderr:      20:            valign: "middle"
[WARNING] stderr: ...
[WARNING] stderr: OSError: Label: File 'assets/nasa.ttf' not found
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 701, in _apply_rule
[WARNING] stderr:     setattr(widget_set, key, value)
[WARNING] stderr:   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
[WARNING] stderr:   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
[WARNING] stderr:   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
[WARNING] stderr:   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/label.py", line 354, in _trigger_texture_update
[WARNING] stderr:     self._create_label()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/label.py", line 347, in _create_label
[WARNING] stderr:     self._label = CoreMarkupLabel(**dkw)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/markup.py", line 94, in __init__
[WARNING] stderr:     super(MarkupLabel, self).__init__(*largs, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 288, in __init__
[WARNING] stderr:     self.resolve_font_name()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 356, in resolve_font_name
[WARNING] stderr:     raise IOError('Label: File %r not found' % fontname)
[WARNING] stderr: 
